version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
workflows:
  version: 2
  test:
    jobs:
      - lint